# Generated by Django 4.2.1 on 2023-10-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSeguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='acta_entrega',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='carta_garantia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='contrato_calibracion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='contrato_mantenimiento',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='cronograma_calibracion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='cronograma_mantenimiento',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='declaracion_importacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='equipo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='etiqueta_caja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='factura_contrato',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='guia_rapida',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='hoja_vida_calibracion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='hoja_vida_mantenimiento',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='manual_servicio_espanol',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='manual_usuario_espanol',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='reportes_calibracion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='reportes_mantenimiento',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='resolucion_invima',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='sede',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='servicio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='ubicacion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
