# Generated by Django 4.2.6 on 2023-11-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSeguimiento', '0002_alter_equipos_acta_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='equipo',
        ),
        migrations.AddField(
            model_name='equipos',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equipos',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
